// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4GPn6Ei6TSa0k6IbWJVVUrX6gydcA2Ho',
    appId: '1:732455365239:web:5fc98b36510ce7c3e2b472',
    messagingSenderId: '732455365239',
    projectId: 'yardsi',
    authDomain: 'yardsi.firebaseapp.com',
    storageBucket: 'yardsi.appspot.com',
    measurementId: 'G-8JWKWCP3XK',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr_f3HsTf6RID0Y-tCD5FcK7nf4O6mxAA',
    appId: '1:732455365239:ios:e49ef8bcc54b83a6e2b472',
    messagingSenderId: '732455365239',
    projectId: 'yardsi',
    storageBucket: 'yardsi.appspot.com',
    iosClientId: '732455365239-5ep6k86kjg222gqmnus47golakl8fhn2.apps.googleusercontent.com',
    iosBundleId: 'com.example.makeSomething',
  );

}